#!/usr/bin/env bash
# Build the PyInstaller Windows EXE and optionally Authenticode-sign with signtool.
#
# Usage (from repo root, e.g. Git Bash on Windows):
#   ./scripts/build.sh --skip-sign
#   ./scripts/build.sh --skip-sign --debug
#   ./scripts/build.sh --skip-sign --app-version 1.0.0 \
#     --update-manifest-url 'https://github.com/N6-Studio/emotiv-controller/releases/latest/download/latest.json'
#
# Monorepo: pass --repo-root /path/to/parent so the Python project is at <root>/python/
#
# Signing (Windows + Windows SDK only): omit --skip-sign and pass either
#   --cert-thumbprint <SHA1>   or   --pfx-path /path/to.pfx
# PFX password: set PFX_PASSWORD in the environment or pass --pfx-password (avoid for CI).
#
# Environment:
#   EMOTIV_PYI_DEBUG=1  — same as --debug (console EXE).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT=""
SKIP_SIGN=0
DEBUG=0
APP_VERSION="0.0.0-dev"
UPDATE_MANIFEST_URL=""
TIMESTAMP_URL="http://timestamp.digicert.com"
PFX_PATH=""
CERT_THUMBPRINT=""
PFX_PASSWORD="${PFX_PASSWORD:-}"

usage() {
  sed -n '1,25p' "$0" | tail -n +2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-sign) SKIP_SIGN=1; shift ;;
    --debug) DEBUG=1; shift ;;
    --repo-root)
      REPO_ROOT="${2:-}"
      shift 2
      ;;
    --app-version)
      APP_VERSION="${2:-}"
      shift 2
      ;;
    --update-manifest-url)
      UPDATE_MANIFEST_URL="${2:-}"
      shift 2
      ;;
    --timestamp-url)
      TIMESTAMP_URL="${2:-}"
      shift 2
      ;;
    --pfx-path)
      PFX_PATH="${2:-}"
      shift 2
      ;;
    --cert-thumbprint)
      CERT_THUMBPRINT="${2:-}"
      shift 2
      ;;
    --pfx-password)
      PFX_PASSWORD="${2:-}"
      shift 2
      ;;
    -h|--help) usage ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

if [[ -n "${EMOTIV_PYI_DEBUG:-}" ]] && [[ "${EMOTIV_PYI_DEBUG}" =~ ^(1|true|yes)$ ]]; then
  DEBUG=1
fi

if [[ -n "$REPO_ROOT" ]]; then
  PYTHON_DIR="$(cd "$REPO_ROOT" && pwd)/python"
else
  PYTHON_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

SPEC_PATH="$PYTHON_DIR/app.spec"
DIST_EXE="$PYTHON_DIR/dist/app.exe"

if [[ "$SKIP_SIGN" -eq 0 ]] && [[ -z "$PFX_PATH" ]] && [[ -z "$CERT_THUMBPRINT" ]]; then
  echo "Provide signing credentials or skip signing explicitly:" >&2
  echo "  --cert-thumbprint '<SHA1>'   (cert in CurrentUser\\\\My), or" >&2
  echo "  --pfx-path '/path/codesign.pfx'   (use PFX_PASSWORD env for password), or" >&2
  echo "  --skip-sign" >&2
  exit 1
fi

if [[ ! -f "$SPEC_PATH" ]]; then
  echo "app.spec not found at: $SPEC_PATH" >&2
  exit 1
fi

run_python() {
  if command -v python3 >/dev/null 2>&1; then
    python3 "$@"
  elif command -v python >/dev/null 2>&1; then
    python "$@"
  elif command -v py >/dev/null 2>&1; then
    py -3 "$@"
  else
    echo "Python not found. Install Python 3 and add it to PATH." >&2
    exit 1
  fi
}

APP_VERSION="${APP_VERSION//[[:space:]]/}"
[[ -n "$APP_VERSION" ]] || APP_VERSION="0.0.0-dev"
UPDATE_MANIFEST_URL="${UPDATE_MANIFEST_URL//[[:space:]]/}"

RELEASE_INFO_PATH="$PYTHON_DIR/_release_info.py"
export _BUILD_RELEASE_INFO_PATH="$RELEASE_INFO_PATH"
export _BUILD_APP_VERSION="$APP_VERSION"
export _BUILD_MANIFEST_URL="$UPDATE_MANIFEST_URL"
run_python -c '
import json
import os
from pathlib import Path
path = Path(os.environ["_BUILD_RELEASE_INFO_PATH"])
av = os.environ.get("_BUILD_APP_VERSION", "0.0.0-dev")
mu = os.environ.get("_BUILD_MANIFEST_URL", "")
body = (
    "# Generated by scripts/build.sh. Do not edit.\n"
    f"APP_VERSION = {json.dumps(av)}\n"
    f"UPDATE_MANIFEST_URL = {json.dumps(mu)}\n"
)
path.write_text(body, encoding="utf-8")
'
unset _BUILD_RELEASE_INFO_PATH _BUILD_APP_VERSION _BUILD_MANIFEST_URL
echo "Wrote $RELEASE_INFO_PATH (APP_VERSION=$APP_VERSION)"

cd "$PYTHON_DIR"

echo "Installing / upgrading pip tooling and PyInstaller..."
run_python -m pip install --upgrade pip setuptools wheel 2>/dev/null || true
run_python -m pip install "pyinstaller>=6,<7"

if [[ "$DEBUG" -eq 1 ]]; then
  export EMOTIV_PYI_DEBUG=1
  echo "PyInstaller: console enabled (--debug)."
else
  export EMOTIV_PYI_DEBUG=0
  echo "PyInstaller: windowed (no console)."
fi

echo "Building EXE with PyInstaller..."
run_python -m PyInstaller --noconfirm --clean app.spec

if [[ ! -f "$DIST_EXE" ]]; then
  echo "Expected output not found: $DIST_EXE" >&2
  exit 1
fi

echo "Built: $DIST_EXE"

if [[ "$SKIP_SIGN" -eq 1 ]]; then
  echo "SkipSign: not signing."
  exit 0
fi

is_windows_build_host() {
  [[ -n "${WINDIR:-}" ]] && return 0
  [[ "${OS:-}" == "Windows_NT" ]] && return 0
  local u
  u="$(uname -s 2>/dev/null)" || u=""
  case "$u" in MINGW*|MSYS*|CYGWIN*) return 0 ;; esac
  return 1
}

find_signtool() {
  local roots=(
    "/c/Program Files (x86)/Windows Kits/10/bin"
    "/c/Program Files/Windows Kits/10/bin"
  )
  local r p candidates=()
  for r in "${roots[@]}"; do
    [[ -d "$r" ]] || continue
    shopt -s nullglob
    for p in "$r"/*/x64/signtool.exe "$r"/*/x86/signtool.exe; do
      [[ -f "$p" ]] || continue
      local ver
      ver="$(basename "$(dirname "$(dirname "$p")")")"
      if [[ "$ver" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        candidates+=("$ver|$p")
      fi
    done
    shopt -u nullglob
  done
  if [[ "${#candidates[@]}" -eq 0 ]]; then
    return 1
  fi
  printf '%s\n' "${candidates[@]}" | sort -t'|' -k1,1Vr | head -1 | cut -d'|' -f2-
}

if ! is_windows_build_host; then
  echo "Authenticode signing requires Windows + Windows SDK (signtool)." >&2
  exit 1
fi

SIGNTOOL="$(find_signtool || true)"
if [[ -z "$SIGNTOOL" ]] || [[ ! -f "$SIGNTOOL" ]]; then
  echo "signtool.exe not found. Install the Windows SDK (Desktop development with C++ / Windows Kit)." >&2
  exit 1
fi

echo "Using signtool: $SIGNTOOL"

sign_args=(sign /v /fd SHA256 /td SHA256 /tr "$TIMESTAMP_URL")

if [[ -n "$CERT_THUMBPRINT" ]]; then
  sign_args+=(/sha1 "${CERT_THUMBPRINT//[[:space:]]/}")
else
  if [[ ! -f "$PFX_PATH" ]]; then
    echo "PFX not found: $PFX_PATH" >&2
    exit 1
  fi
  sign_args+=(/f "$PFX_PATH")
  if [[ -n "$PFX_PASSWORD" ]]; then
    sign_args+=(/p "$PFX_PASSWORD")
  else
    echo "PFX password required: set PFX_PASSWORD or pass --pfx-password" >&2
    exit 1
  fi
fi

sign_args+=("$DIST_EXE")

echo "Signing $DIST_EXE ..."
"$SIGNTOOL" "${sign_args[@]}"

echo "Signed successfully."
echo "Verify (PowerShell): Get-AuthenticodeSignature -FilePath '$DIST_EXE'"
